head(PERAGGR, n = 1)
summary(PERAGGR$EFFSIZE)
hist(PERAGGR$EFFSIZE, col = 'green')
boxplot(PERAGGR$EFFSIZE, col = 'red')
t.test(PERAGGR$EFFSIZE)
qqnorm(NAICExpense$EXPENSES)
qqline(NAICExpense$EXPENSES)
logEXPENSES = log(NAICExpense$EXPENSES)
qqnorm(logEXPENSES)
qqline(logEXPENSES)
